"""change models.py

Revision ID: 5ccdf8569d84
Revises: 61072be6068c
Create Date: 2025-04-17 08:53:48.527300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ccdf8569d84'
down_revision: Union[str, None] = '61072be6068c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('area_address_with_zipcode_area_id_fkey', 'area_address_with_zipcode', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('area_address_with_zipcode_area_id_fkey', 'area_address_with_zipcode', 'sapporo_city_area', ['area_id'], ['id'])
    # ### end Alembic commands ###
