"""fix: area column without FK

Revision ID: ce5df50676b0
Revises: 158532e16373
Create Date: 2025-04-16 08:04:15.146217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce5df50676b0'
down_revision: Union[str, None] = '158532e16373'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('municipality_code', sa.String(), nullable=True),
    sa.Column('municipality_name', sa.String(), nullable=True),
    sa.Column('furigana', sa.String(), nullable=True),
    sa.Column('postal_code', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('contact_person', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('payment_status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('area_address_with_zipcode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area', sa.String(), nullable=True),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.Column('area_en', sa.String(), nullable=True),
    sa.Column('postalcode', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['sapporo_city_area.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('area_address_with_zip')
    op.drop_constraint('area_sorting_area_fkey', 'area_sorting', type_='foreignkey')
    op.alter_column('area_sorting', 'area',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.add_column('sapporo_city_area', sa.Column('area_id', sa.Integer(), nullable=True))
    op.add_column('sapporo_city_area', sa.Column('ward_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sapporo_city_area', 'ward_id')
    op.drop_column('sapporo_city_area', 'area_id')
    op.create_foreign_key('area_sorting_area_fkey', 'area_sorting', 'sapporo_city_area', ['area'], ['id'])
    op.alter_column('area_sorting', 'area',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.create_table('area_address_with_zip',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('area', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('area_en', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('postalcode', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['area'], ['sapporo_city_area.id'], name='area_address_with_zip_area_fkey'),
    sa.PrimaryKeyConstraint('id', name='area_address_with_zip_pkey')
    )
    op.drop_table('area_address_with_zipcode')
    op.drop_table('admin_info')
    # ### end Alembic commands ###
