"""add address column

Revision ID: eb4669307651
Revises: 6c7932bf13b0
Create Date: 2025-04-17 07:33:05.503596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb4669307651'
down_revision: Union[str, None] = '6c7932bf13b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_info', sa.Column('note', sa.String(), nullable=True))
    op.add_column('area_address_with_zipcode', sa.Column('address', sa.String(), nullable=True))
    op.add_column('area_address_with_zipcode', sa.Column('zipcode', sa.String(), nullable=True))
    op.drop_column('area_address_with_zipcode', 'postalcode')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('area_address_with_zipcode', sa.Column('postalcode', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('area_address_with_zipcode', 'zipcode')
    op.drop_column('area_address_with_zipcode', 'address')
    op.drop_column('admin_info', 'note')
    # ### end Alembic commands ###
